### ISSUE TITLE
Downloading Zip File Issues.ZIP

### ISSUE THREAD

**Issue by dribblej** [OfficeDev/Project-Accelerator#11]
Hello, 

I tried to download your unmanaged solution of issues_0_0_0_3. By default my Mac uncompresses your solution. I re compressed the 3 items: 

- [Content_Type].xml
- customizations.xml
- solution.xml

and then I tried to import them in PowerApps -> solutions -> import. I cannot fully upload the solution with these flows because of the error 

> "Error code
80040216
Exception message
Error while importing Calculated fields name cr491_age"

Is there something I can do about this? These flows, if they work, are currently the best option for notifying users outside of project for the web given its notification limitations to the assigned to field of tasks within projects. 

Thank you for your time, 
Josh

**Comment by BeReasonable** [comment]
I've updated the repo to use a more recent version of the solution
