### ISSUE TITLE
Unable to install solution

### ISSUE THREAD

**Issue by ricetristan** [OfficeDev/Project-Accelerator#15]
I've downloaded the **Project for the web Accelerator v1_6_0_12.zip** and am attempting to install via the Power Apps admin center using Global Administrator credentials.  However, when I try to import the solution I'm getting the following error:

_There are missing dependencies. Install the following solutions before installing this one: "msdyn_ProjectServiceCore (1.0.0.87)"._

I have enabled the Microsoft Project Service Core Dynamics 365 app and I can see that the msdyn_ProjectServiceCore solution is installed, and it shows version 1.0.0.87

Is there something else I'm missing?  Thanks!

**Comment by johnalindogan** [comment]
@ricetristan have you tried importing the accelerator to a non-default production environment? I am also encountering the same issue on my default environment. however, when I created a separate production environment the import went thru

**Comment by ricetristan** [comment]
@johnalindogan yes I tried also importing into a non-default environment and had the same issue (along with several other missing dependencies there).

**Comment by ricetristan** [comment]
Another follow-up here - I was able to bypass the 'missing dependencies' error by simply removing all of the <MissingDependency> entries in the solution.xml file.  However, the import now fails with the following error instead (after processing for a while longer):

_Attribute proj_prioritizationscore is a Integer, but a Decimal type was specified._

In checking the Projects table in the dataverse, I do see that the column Prioritization Score is indeed a Whole Number rather than a Decimal type.  An attempt to delete this column and re-add it with the new type fails due to other dependencies.

**Comment by joelarscheid** [comment]
If you get a message saying “There are missing dependencies. Install the following solution before installing the one: “msdyn_ProjectServiceCore (1.0.0.87)”

Try going to the Power Apps Admin Center and Update the Project Service App to the latest version and repeat the import.

**Comment by ricetristan** [comment]
@joelarscheid I've already done that, and we're on the latest version.

**Comment by ricetristan** [comment]
Just a follow-up here - I can't be certain, but believe this issue was being caused by an unmanaged solution that we had previously installed in our Default environment.  I deleted that, and also had to manually revoke several changes it had made (including that proj_prioritizationscore column on the Projects table), and was finally able to install this solution.  Hopefully at some point in the future MS provides functionality to remove customizations for components of type Entity via the Solution Layers.
