### ISSUE TITLE
Cannot add a Project to a Program - update operation on msdyn_project 

### ISSUE THREAD

**Issue by matherton-pen** [OfficeDev/Project-Accelerator#22]
When I add a project to a program, either from editing the project screen or from editing the program one and adding existing from there, I get the below error. Everything else is editable that I try, but this just isn't working.  Any help appreciated

![image](https://user-images.githubusercontent.com/80957413/112169922-8979c880-8bea-11eb-8ac8-87c03ccce2fe.png)

**Comment by tjonkim** [comment]
I am getting the same error message, and I also get this error message when I try to update the Description field

**Comment by anitobaker** [comment]
hi guys. this was mentioned in the readme as a critical Project for the Web bug. Hoping we can get an update on the fix though! the Program and Business Case functions would be awesome but currently they are not usable. 
![image](https://user-images.githubusercontent.com/82130234/113958877-65f28700-9854-11eb-951b-4c224b5e5ddd.png)

**Comment by BeReasonable** [comment]
We are deploying a fix to this now. It impacts the Project Core solution. You'll need to manually update the solution to get it. The following Dynamics regions have the updated solution. It will be available globally over the next three weeks.

CAN
SAM
IND
FRA
UAE
ZAF
GER
CHE

**Comment by ricetristan** [comment]
@BeReasonable should we see this Project Core update available in the US?  Not seeing any update available here (via the Power Platform admin center, then Dynamics 365 Apps for our environment), and we're still struggling with this bug.

**Comment by BeReasonable** [comment]
> @BeReasonable should we see this Project Core update available in the US? Not seeing any update available here (via the Power Platform admin center, then Dynamics 365 Apps for our environment), and we're still struggling with this bug.

The latest solution is available in the US now. Let me know if you don't see it.

**Comment by ricetristan** [comment]
I can confirm that the Project Core update hit our tenant last week and we were able to update and resolve this bug.  Thanks!

**Comment by matherton-pen** [comment]
yup I also can do this now, not sure if related to new Core version of the solution update I did last night, but it works. So thank you
