### ISSUE TITLE
Upgrade from version 1.4.0.3

### ISSUE THREAD

**Issue by nicolasmattioni** [OfficeDev/Project-Accelerator#23]
Not an issue but more a question :
Is it safe to upgrade the whole solution from 1.4.0.3 to the latest version ?
Are we going to loose the customizations done on the current version ?

Thanks.

**Comment by matherton-pen** [comment]
If you have made customisations in separate solutions, then upgrading this one should be fine.  Emphasis on should though, no one can guarantee as depends on what updates there are in their solution.

**Comment by BeReasonable** [comment]
That's right. Customizations should be made it separate solution layers.
