### ISSUE TITLE
Project Accelorator .pbix not showing data in workspace

### ISSUE THREAD

**Issue by dribblej** [OfficeDev/Project-Accelerator#35]
Hello, 

Im not sure if this is the right place to work out this issue but, I have the first-gen OOB .pbit for Project for the Web, and the new one in a workspace in power bi service. As of Friday, the reports are showing up blank, even though there are numerous projects in my database and they showed up fine on these reports in the past. 

The data shows up in Power Query when looking at this .pbix files on the PBI desktop, however, on the reports themselves, everything is blank.

**Comment by Zajc** [comment]
Hello Dirbblej. Did you setup a schedule refresh or Try to click Refresh now on Dataset.

**Comment by BeReasonable** [comment]
hi @dribblej , are the credentials you're using to refresh the data the same that you login to manage projects with?
