### ISSUE TITLE
Open in Project button missing

### ISSUE THREAD

**Issue by jonesadj** [OfficeDev/Project-Accelerator#38]
I've deployed the solution successfully and everything works.  However, the "Open in Project" button is missing from the command bar in the Project entity form.  Is there something that needs to be done as part of deploying the solution or could this be a bug?

**Comment by BeReasonable** [comment]
Hi @jonesadj , what kind of environment have you deployed the Accelerator into? You'll only see that button if Project has been deployed into the Default environment. If you've deployed into a Production dataverse instance, then you won't see the button.

**Comment by daviduber1** [comment]
Hi @BeReasonable, we have also come across this issue. We have Accelerator deployed in a named environment. Are you able to share any options for enabling this is a production dataverse environment? It appears to be the case at https://youtu.be/NF2M9F4mRbU?t=1415 that it is enabled in a named environment.

**Comment by IanMcV** [comment]
Thankyou @BeReasonable.  I had noticed that this was missing also but hadn't put 2 and 2 together here.  Appreciate the update.  Now I know the behavior I can accommodate

**Comment by BeReasonable** [comment]
> Hi @BeReasonable, we have also come across this issue. We have Accelerator deployed in a named environment. Are you able to share any options for enabling this is a production dataverse environment? It appears to be the case at https://youtu.be/NF2M9F4mRbU?t=1415 that it is enabled in a named environment.

Hi @daviduber1 , this video shows the Accelerator in the Default environment. The Open in Project button is currently unsupported in Named instances/environments

**Comment by joshbooker** [comment]
Not sure why it's unsupported but it does appear to be explicitly disabled for named CDS environments:
![image](https://user-images.githubusercontent.com/2698896/142953856-caba23e6-4ad2-4e12-8bc9-cd0bd79ce863.png)
May work to simply delete this display rule using ribbon workbench.

**Comment by IanMcV** [comment]
Thanks @joshbooker, that is an interesting find.  I might have a look at this myself later today
