### ISSUE TITLE
Error 80040220 when importing Project_for_the_web_Accelerator_v1_7_0_3 in Power Apps

### ISSUE THREAD

**Issue by Tmakaizen** [OfficeDev/Project-Accelerator#41]
Hi,

I have a P5 project online license and trying to set up Project for the Web Accelerator but I couldn't go past the import part. I'm encountering a permission error Error 80040220.

I called our service desk and they installed Dynamics 365 but the error remains.

Help.

Thanks
Tmak

**Comment by BeReasonable** [comment]
Are you still running into this issue? Have you followed [the instructions here](https://aka.ms/deployproject) to get started with your Project deployment?
