### ISSUE TITLE
Permission Levels

### ISSUE THREAD

**Issue by KevinChambers** [OfficeDev/Project-Accelerator#42]
In the Project Online world there were a number of roles such as the following:
•	Project Online - Admin 
•	Project Online - PMs 
•	Project Online – Portfolio Viewers 
•	Project Online – Portfolio Managers 
I assume we will need to create custom roles to achieve similar results.  Would it be possible to get a base recommendation as to which tables and permission levels would achieve similar results as part of the Wiki documentation?

**Comment by BeReasonable** [comment]
Hi @KevinChambers,
Custom roles are well-suited for any custom fields and tables that you're using. However, for core fields and tables (project, tasks, teammember, etc), customizing security can lead to an adverse experience for users.
