### ISSUE TITLE
Tasks subgrid height uses VH instead of %, causing unneeded scrolling and duplicate scrollbars

### ISSUE THREAD

**Issue by daviduber1** [OfficeDev/Project-Accelerator#43]
Currently the tasks subgrid iframe uses _height="100vh"_, which causes scrollbars within scrollbars by making the iframe as large the browser window itself. If it instead uses _height="100%"_ the task subgrid renders perfectly with usable scrollbars. I am happy to be contacted about this issue - screenshots etc.

I have verified this issue across multiple tenants and environments, and I suspect may have been introduced in the July project core updates, as Accelerator hasn't been modified in the past couple of months except for last week's update.

[Current behaviour](https://excopartners-my.sharepoint.com/:v:/p/david_uber/ER9WY7RtAQ1LleZR_Y3-d5gBgEWTKK8AwjPCCZRAJpCrZg?e=LDbZzy)

[Old behaviour](https://excopartners-my.sharepoint.com/:v:/p/david_uber/EWnYMX-QsMdIlrqxRAPagEABUyS21XSSj6jEeo5B7SJICA?e=DVC4qb)

**Comment by BeReasonable** [comment]
Thank you for sharing this, @daviduber1 ! 
I'll pass it along to the rest of the team for reviewing if it should go in the Project Core solution.
