### ISSUE TITLE
task view does not show anything but "login@microsoft.com refused to connect"

### ISSUE THREAD

**Issue by chimuzo** [OfficeDev/Project-Accelerator#45]
[PPM Task View Issue.pdf](https://github.com/OfficeDev/Project-Accelerator/files/7269193/PPM.Task.View.Issue.pdf)

It still doesn't work after following the steps in the error link.  However, if I open the project using Project for the Web first, and then go back to Power Platform, the tasks show up.

**Comment by BeReasonable** [comment]
There are a few things to try to resolve this.
1. Enable third-party cookies in your web browser.
2. Clear the browser cache (including cookies) and try logging in again
