### ISSUE TITLE
Modify choice field

### ISSUE THREAD

**Issue by leozak06** [OfficeDev/Project-Accelerator#47]
Hi there, I am looking for a way to be able to add to the state choice fields and/or replace the existing choice values. 

I tried to import the solution as unmanaged by unzipping the solution file > going into the solution.xml file to change the <managed>1</managed> property from 1 to 0 > zipping the file again but importing the updated solution file gave me the following error:
**Site Map import: FAILURE: unmanaged solution expects full siteMapXml**

Prior to that, I actually replaced some of the proj_state choice field values and added new values also but importing to another sandbox environment actually does not overwrite the existing proj_state choice field but adds to the list with my new values which is not ideal. See below example.

**Original values**
- (1) Proposed
- (2) Active
- (3) Closed
- (4) On Hold

**New values** 
- (1) Choice 1
- (2) Choice 2
- (3) Choice 3
- (4) Choice 4
- (5) Choice 5

**Values deployed to target environment as**
- (1) Proposed
- (2) Active
- (3) Closed
- (4) On Hold
- (1) Choice 1
- (2) Choice 2
- (3) Choice 3
- (4) Choice 4
- (5) Choice 5

Is there a better way to do this? What is the best practice?

Appreciate all the help! Thank you!

**Comment by DanielMonger** [comment]
@leozak06  Sorry that didn't help. I have had occasions where no matter what I can't get the optionset to change and resort to changing said options in the environment where they are required directly in the table menu (not via a solution)

**Comment by AndrewJNorris** [comment]
Hi folks, does it really matter that you're renaming the original values if you're using a solution layer? The new solution containing your changes can just be removed to restore the values in the underlying Project Accelerator solution if needed.
