### ISSUE TITLE
Managed solution

### ISSUE THREAD

**Issue by RobEricsson** [OfficeDev/Project-Accelerator#48]
Hi there
I have just downloaded and installed the latest version of the Accelerator.
All worked fine, however this is a Managed solution so cant be modified ... I cannot even update the Reports web resource.
Could you reissue as an unmanaged solution please?
Thanks

Rob

**Comment by RobEricsson** [comment]
Serco Business

Hi Josh

Thanks very much for your response .. much appreciated.

I already tried setting the Managed flag to 0. Unfortunately the solution still doesn't import. It gives the error message:

Site Map import: FAILURE: unmanaged solution expects full siteMapXml

Regs

Rob
From: Josh Booker ***@***.***>
Sent: 19 October 2021 21:01
To: OfficeDev/Project-Accelerator ***@***.***>
Cc: Ericsson, Rob (Group) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/Project-Accelerator] Managed solution (Issue #48)

ATTENTION EXTERNAL

you can unzip and mark in unmanaged (see #24<https://secure-web.cisco.com/1q0vJxYj0yVzoP2g_r7I7GXxve3ldb5ha4GowfOsAZpLVWwFhQM41ZX5lE2KcYqlIcNhjgw6yo33925-o33xZHm1IAiGsskT9BNJDcDzwJnXO4xp9FJdJfOiQU7PbO3ksyOPt8LnPt1lTJjEmvvC-if3AfJGWIU0zdn2YBNZ2nxjN8oqnI97s2KzKqbRXFEhYRXBME4WLm-vaidUGqIXfE07rECP-a-tYKhfsk1Qq-b82WBiLXB44YufuRJAlByySOnDlNIJypmaLke33dMvW8SeJpdslrfdSX5_Ocv3TuyzquuufQppmBz4USG7Kk0-x/https%3A%2F%2Fgithub.com%2FOfficeDev%2FProject-Accelerator%2Fissues%2F24>) - but yeah that should be in the ReadMe.md
#24<https://secure-web.cisco.com/1q0vJxYj0yVzoP2g_r7I7GXxve3ldb5ha4GowfOsAZpLVWwFhQM41ZX5lE2KcYqlIcNhjgw6yo33925-o33xZHm1IAiGsskT9BNJDcDzwJnXO4xp9FJdJfOiQU7PbO3ksyOPt8LnPt1lTJjEmvvC-if3AfJGWIU0zdn2YBNZ2nxjN8oqnI97s2KzKqbRXFEhYRXBME4WLm-vaidUGqIXfE07rECP-a-tYKhfsk1Qq-b82WBiLXB44YufuRJAlByySOnDlNIJypmaLke33dMvW8SeJpdslrfdSX5_Ocv3TuyzquuufQppmBz4USG7Kk0-x/https%3A%2F%2Fgithub.com%2FOfficeDev%2FProject-Accelerator%2Fissues%2F24>

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1V0pjx8i00fjhdootMSFSFTtAKnDYO36sx4-iehq08SFHC_qLsDDmBs2Ai2rKEQEHwPVSWeksKEZcZpz3p0z6h_AdR2fWpBlOxFYrroISe9H0fBaezbQzkhO2zXi1_DXO8vZtAmUoz6X6mkN2-UYF8Ac4RLX9iRlEfHxFj60bACGg6H0MVPeI6E9JUyoLM_486WBw29d-Sk8uUsgulQvpjDNa6wGmdRdztng3OTpZrSorB_h993WlK1KkSxmYIM4ljxhr2ujIm9LKCQl49XcGt3t_R896rdOKUa3rJRbqKYrbeghl35wcgoamb3uFAUIj/https%3A%2F%2Fgithub.com%2FOfficeDev%2FProject-Accelerator%2Fissues%2F48%23issuecomment-947061222>, or unsubscribe<https://secure-web.cisco.com/13BMAtxqZGvl0cVgGQfbFXRZQDiQGIbJxD3fXrcG3HPIigzkmjqv0Z3woV1JfTvukwPU0AdwpCZcl-XjERaQfiXALSG6cxP58sU3XAjqqnKFhkp9Iw5l4q37iFpA917h0_Ejm7LUAVic0jqZ-GI88Z_nBUY193vyHjCuQXKr0oLkyE5IiTpbS8x5pUPJ9lAAoftO69NXdG8yaeG1JILmQHi-7h0bliyU3FbJSCFlw2B64CAA3KIB6hZSEQLFbQr1uNceC-ijZmz65BfxpeEptMjhxQn9MCMvXf0lDfzovoRpFdoThsqkJan2am3ycG09D/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABZXNEAZVSJISSAX7OQUAALUHXE6ZANCNFSM5GJDM3PQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by RobEricsson** [comment]
Serco Business

Again, thanks for taking the time to respond to me.
Hopefully an unmanaged solution will be released soon ...

Regards
Rob

From: Josh Booker ***@***.***>
Sent: 20 October 2021 15:29
To: OfficeDev/Project-Accelerator ***@***.***>
Cc: Ericsson, Rob (Group) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/Project-Accelerator] Managed solution (Issue #48)

ATTENTION EXTERNAL

Haven't tried unmanaged yet sorry. There may be a simple fix but I'm not sure. Yeah they should release a tested unmanaged version

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1pnHYqjCHjR5R6BriuwLAnqvaL7XKO05ztul1xYEEoQN_ydPdECF2Pi9KgP91W5LEZrJjJcKdWEGc489LCPr7heq4knIlcrRuRPktOwNC0vJmBSkm1gsR7dLdxcgkwGlA_FXi8z-0tjAaw7Mntdo-BgTaU5K3Mv1lEibA74u8uLuHEgdtOHHUarUYTBfgv_v6aKqXk7yncxtCwEVQoUw14zQNWS-W0fAKKFDnIK-18trZR8dO76Nu9raW4yM6wzs991BNqP6R_Zi71rufQTRQcKalW9_djKZ_fE5-kQvL6rW5Dqv-fKEvwU4Lp9R4SA7t/https%3A%2F%2Fgithub.com%2FOfficeDev%2FProject-Accelerator%2Fissues%2F48%23issuecomment-947723895>, or unsubscribe<https://secure-web.cisco.com/1T7wj9beGf9IwTW69F2-nMEsOUNTYzTvu4PxFBE3UfQxGlo-dxZJebjvhi60kr9rsSe1mbOvoCw1D6cyZrl8uy0o_Vdo7AtDblllRZJpDntRLgJBZ-sM4RZ9KFkajJv5L7ehQAnkdnL-m7tvc_5ZWvUxbmXjBPmEiwDvnJuMek2uupO2_vqDtgBCpuB02iAWGe7EmEcGHQug8FyUvzfTW9rHP-8pA7sj05eL1As9BcT36BOAhf2aFkExIbnhJrTYVeOM-Jf91O5TYJFzCvj8U3CYvR0W4RuhQPUcI2j7qdMBQHk7Hld7N0G7IrAq0f5cg/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABZXNEFUPTCJ7VF3NYEYMLLUH3G3LANCNFSM5GJDM3PQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by ndrogo** [comment]
> Hi Rob and Josh,
> 
> I believe best practice/expected practice here is to create your own solution that lays on top of the managed project accelerator solution - this way your modifications are captured in a single solution (or set of solutions) while the Project Accelerator solution remains the gold/master copy of itself.
> 
> This allows fairly broad modification of Project Accelerator, with the exception of project core components of course.
> 
> Cheers, David

@daviduber1   Would you be able to point me to any tutorials on how to create my own solution that lays on top so I can modify and added choices to the accelerator?

**Comment by AndrewJNorris** [comment]
@ndrogo, if you don't already have one, you'll need to create a dev environment and import Project Accelerator into it so you can create the solution in there then export it and import to your test/prod environments.
Dev is just a name not a specific mode of environment.
Have a look at this vid, it's a bit out of date as Power Apps has had a few changes since then so the forms might look a bit different but the concept is still sound and correct.
https://www.youtube.com/watch?v=bAootc3AF4Y

**Comment by joshbooker** [comment]
Here are the docs to create a solution and 'Add Existing' components that you want to modify:
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-solution
@AndrewJNorris makes a very good suggestion to use a separate environment for dev/test which will reduce the possibility of publishing breaking changes to your production environment.  Just know it optional as you can create a solution directly in the prod environment if you'd like.

**Comment by ndrogo** [comment]
Do I need to do this to just change the drop down choices?  If yes once I have them how do get them into production?
Nick

**Comment by joshbooker** [comment]
If the column choices are editable in the managed solution then yes you need to add the table to a unmanaged solution, make the changes and then publish the solution.  Publishing applies the changes.  Its in the article.

**Comment by AndrewJNorris** [comment]
@ndrogo, I'd suggest making any changes via a solution rather than direct, then they're simple to remove.
If you edit directly you might be blocking yourself from taking any updated versions of the accelerator as and when the MS team release them.
Direct editing of the choice fields probably won't block this path for you but as you get more confident and start making other changes you might run into issues during upgrades so it's best to get into the habit of using solution layers.

**Comment by ndrogo** [comment]
Site Map import: FAILURE: unmanaged solution expects full siteMapXml  is
the error I got when I made it unmanaged and tried to import.  I created a
sandbox environment added project and then tried to add the solution. Any
ideas?

Nick

**Comment by joshbooker** [comment]
Nick, You don't have to make the managed solution unmanaged.  Instead you import the managed solution as usual then create a new empty unmanaged solution and 'Add existing' items such as tables forms etc.  These items will now be editable in the unmanaged solution.

**Comment by BeReasonable** [comment]
In terms of getting the reports working, the instructions in the README have been updated with guidance about creating a new solution layer. 

For customizations in general, they need to be made in a new solution layer.
