### ISSUE TITLE
Resource Scheduling App

### ISSUE THREAD

**Issue by joshbooker** [OfficeDev/Project-Accelerator#49]
Is there any info available on the URS feature availability included in P4W?
More specifically:
https://powerusers.microsoft.com/t5/Power-Platform-and-Dynamics-365/Universal-Resource-Scheduling-in-Project-for-the-Web/m-p/1304454#M401

**Comment by BeReasonable** [comment]
Hi @joshbooker, is this a question about the Accelerator, or the Project Core solution?

**Comment by joshbooker** [comment]
@BeReasonable Thanks for your reply.  The question is about the Resource Scheduling Solution which is a part of P4W but I've been unable to find the appropriate support venue for that for over a month now.  Or any documentation on the solution pertaining to PW4 for that matter.  If you could point me in the right direction that'd be great.

**Comment by BeReasonable** [comment]
Hi @joshbooker, URS is supported within the Resource Scheduling App, and not within the Project model-driven app.

**Comment by joshbooker** [comment]
Thanks but where exactly is 'within the Resource Scheduling App'?
