### ISSUE TITLE
Task Grid error

### ISSUE THREAD

**Issue by leozak06** [OfficeDev/Project-Accelerator#50]
<img width="935" alt="Task Grid" src="https://user-images.githubusercontent.com/22460241/138485034-6b56c994-02b7-4a4a-9a83-2a3fef2738ef.PNG">

Good morning, We are trying to use the task grid in project accelerator, however getting the following error: 

**To use this view, you must have browser popups enabled. More information** 

I enabled popups but am continuing to get this error. Is there are way to prevent this so all our users don't come across it?

Please let me know! Thanks in advance.

**Comment by BeReasonable** [comment]
Hi @leozak06 , are you still running into this issue?
