### ISSUE TITLE
Projects aren't in PWA

### ISSUE THREAD

**Issue by matherton-pen** [OfficeDev/Project-Accelerator#52]
Since installing the accelerator, we now have hundreds of projects within it which is great and it generally works well for us. However I notice that when I go to PWA (https://XXXX.sharepoint.com/sites/pwa) this is totally empty which seems very odd!

How do I get my projects from the accelerator into the PWA? 

The reason I want to do this is to open some of the projects within the desktop client to get around the 500 task limit within Project Online, which requires the project to be within PWA from what I read

**Comment by BeReasonable** [comment]
Hello. The Accelerator is a customization of [Project For the Web](https://support.microsoft.com/office/what-is-project-for-the-web-c19b2421-3c9d-4037-97c6-f66b6e1d2eb5?ui=en-us&rs=en-us&ad=us). It doesn't integrate with Project Online.
