### ISSUE TITLE
Is there any option if we can set the url  https://project.microsoft.com/  to use any other environment than default environment

### ISSUE THREAD

**Issue by pre-alt** [OfficeDev/Project-Accelerator#54]
**Question --** " I have installed project in a different environment and now wanted to access it hence wanted to know if I can access the project via Project.microsoft.com, and can it be changed to the new environment where the project stuffs are installed." 
 
Analysis --
As per the Analysis found that in non-Default environment, projects can be created and managed through the Project Power App. Users with the Project User and Project Common roles will see the Project app tile appear in Dynamics Home. Here the non default environments refers to developer which you can take. Hence I am afraid that will not be able to change the environment. Found the following article to know how we can deploy project to new environment like Developer : as we do not have an option to change the default to developer environment :
https://docs.microsoft.com/en-us/project-for-the-web/deploying-project#provisioning-a-new-environment-1

Ask 
====
Hence need a confirmation on whether there is any option if we can set the url  https://project.microsoft.com/  to use any other environment than default environment.

Else is there a option for a url for any other environment we install project? If there is option to have the same look and feel when we use https://project.microsoft.com/

**Comment by BeReasonable** [comment]
Today, only the Project Power App is available outside of the Default environment
