### ISSUE TITLE
Successfully installed, but where to start with "Request" etc.

### ISSUE THREAD

**Issue by BramdVries** [OfficeDev/Project-Accelerator#58]
Thanks for creating the accelerator, I'm looking forward to exploring Project for the Web with it.

After installing, I indeed can see an empty dashboard the Readme.md alludes to:
"The Project Power App in this environment will look similar to the screenshot below."

But where do I start with "Converting a Project Request into a Project using Power Automate". I don't see any clues in my PowerApps environment, nor do I seem to be able to add this P4W accelerator to my Teams.

Or is it possible that a previously provisioned P4W is interfering with this accelerator?

**Comment by Zajc** [comment]
1. The dashboard will be filled when you will create Projects, Requests....
2. If you started the process "Converting a Proejct Request into a Proejct using Power Automate" then: Process will start wnen you will create or edit the request, change the Request status to Approved and save the request. in this case process will automatically create Project from saved Request
3. For the solution to work properly you need to deploy "Microsoft Project Service Core" (Project for the web) + Project for the web accelerator on top.

**Comment by BramdVries** [comment]
Hi Zajc, thanks for your reply. 
After importing the accelerator, I see now that "Requests", "Project requests" is missing from the navigation bar on the left hand side. 
(I did verify that Core etc. is installed)
Could it be that b/c my interface is Dutch, the accelerator doesn't install properly? Other things to check?
Thanks,
Bram
![Screenshot 2022-03-07 Power apps solutions installed](https://user-images.githubusercontent.com/46865017/157017332-7565b595-9db9-4d93-aafd-323fa75e0492.jpg)

**Comment by Zajc** [comment]
Hi, You are in make.powerapps.com (This is creator/development interface). Can you go to the Apps in left navigation and run the Project Application. When entering the app, you should see the Project app navigation. Project for the web Accelerator is not localized.

**Comment by BramdVries** [comment]
So, I'm in a completely EN-US environment (Windows 10, Microsoft 365), but when importing the Accelerator, for some reason Dynamics365 decided to be in NL-NL.... So after forcing Dynamics to English using these [instructions](https://portal.dynamics365support.com/knowledgebase/article/KA-01201/en-us), the navigation in the app has all the items. But some with localized terminology, some in English....
![Screenshot 2022-03-07 after changing language to English](https://user-images.githubusercontent.com/46865017/157079645-4fd39c97-38d6-40c4-916b-01c7cf8b3896.jpg)

So I'm good to go and show this to a prospect. Hopefully no further surprise...

**Comment by Zajc** [comment]
You should be able to set the language to English in Settings, Personalization Settings, Language... 
![image](https://user-images.githubusercontent.com/47420780/157109422-d9100f2a-a877-4e65-8685-7c73943cb0cf.png)

Otherwise here is the procedure setting up Project in multiple languages:
1. Create environment
2. Add required languages (this should be done before step 3)
3. Add Microsoft Project Service Core
If you add Accelerator, the Environment should be in English as Accelerator is not fully translated.
