### ISSUE TITLE
Import Failure - Privilege

### ISSUE THREAD

**Issue by dabaggett** [OfficeDev/Project-Accelerator#61]
Solution "Project for the web Accelerator" failed to import: OptionSets import: FAILURE: SecLib::CheckPrivilege failed. User: b7709522-2a25-e911-a983-000d3a170d67, PrivilegeName: prvCreateOptionSet, PrivilegeId: e62439f6-3666-4c0a-a732-bde205d8e938, Required Depth: Basic, BusinessUnitId: 1850c35b-7421-e911-a983-000d3a170d67, MetadataCache Privileges Count: 4892, User Privileges Count: 1026

Can you tell me what privilege to request?

**Comment by BeReasonable** [comment]
Ensure the user importing the solution has Admin privileges for the environment.
