### ISSUE TITLE
Create a Business Process Flow

### ISSUE THREAD

**Issue by alligator4480** [OfficeDev/Project-Accelerator#94]
Hello,

I can't seem to get my newly created **Business Process Flow** to appear?

Steps I've taken

1. created a new "Business Process Flow" Automation inside my existing **Unmanaged Solution** - within "Solutions".
2. my "Primary Entity" is pointing to the existing "project" table.
3. created the "flow".  Saved, validated and Activated (with no errors).

When i refresh "my projects", im not seeing the newly created Header (in red).

What am i doing wrong? (screenshot below)

![Process__BProcess_Flow_-_Microsoft_Dynamics_365](https://github.com/OfficeDev/Project-Accelerator/assets/143005781/0a3c36ac-1c78-45b3-8f73-5dcc1738f268)

1. Is there a step AFTER you created and activate the flow, that needs to happen?
2. I wonder if I've pointed to a wrong Table?

thank you

**Comment by mm2221** [comment]
Hi there, 
did you "publish all customizations" and then refreshed the model-driven app to see changes?
